<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from activity-entity/xml/schema/CRM/ActivityEntity/EntityActivity.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:750ffe66f799971b1bc330ddab9d70ac)
 */
use CRM_ActivityEntity_ExtensionUtil as E;

/**
 * Database access object for the EntityActivity entity.
 */
class CRM_ActivityEntity_DAO_EntityActivity extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_entity_activity';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ActivityEntity ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Activity
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $activity_id;

  /**
   * Physical table name for entity being joined
   *
   * @var string|null
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_table;

  /**
   * FK to entity table specified in entity_table column.
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_id;

  /**
   * Determines the type of connection
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $record_type_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_entity_activity';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Entity Activities') : E::ts('Entity Activity');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'activity_id', 'civicrm_activity', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Dynamic(self::getTableName(), 'entity_id', NULL, 'id', 'entity_table');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Activity Entity ID'),
          'description' => E::ts('Unique ActivityEntity ID'),
          'required' => TRUE,
          'where' => 'civicrm_entity_activity.id',
          'table_name' => 'civicrm_entity_activity',
          'entity' => 'EntityActivity',
          'bao' => 'CRM_ActivityEntity_DAO_EntityActivity',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'activity_id' => [
          'name' => 'activity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Activity ID'),
          'description' => E::ts('FK to Activity'),
          'where' => 'civicrm_entity_activity.activity_id',
          'table_name' => 'civicrm_entity_activity',
          'entity' => 'EntityActivity',
          'bao' => 'CRM_ActivityEntity_DAO_EntityActivity',
          'localizable' => 0,
          'FKClassName' => 'CRM_Activity_DAO_Activity',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Activity"),
          ],
          'add' => NULL,
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Table'),
          'description' => E::ts('Physical table name for entity being joined'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_entity_activity.entity_table',
          'table_name' => 'civicrm_entity_activity',
          'entity' => 'EntityActivity',
          'bao' => 'CRM_ActivityEntity_DAO_EntityActivity',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Entity table"),
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'activity_used_for',
            'optionEditPath' => 'civicrm/admin/options/activity_used_for',
          ],
          'add' => NULL,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Entity ID'),
          'description' => E::ts('FK to entity table specified in entity_table column.'),
          'required' => TRUE,
          'where' => 'civicrm_entity_activity.entity_id',
          'table_name' => 'civicrm_entity_activity',
          'entity' => 'EntityActivity',
          'bao' => 'CRM_ActivityEntity_DAO_EntityActivity',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Entity ID"),
          ],
          'add' => NULL,
        ],
        'record_type_id' => [
          'name' => 'record_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Connection Type'),
          'description' => E::ts('Determines the type of connection'),
          'required' => FALSE,
          'where' => 'civicrm_entity_activity.record_type_id',
          'table_name' => 'civicrm_entity_activity',
          'entity' => 'EntityActivity',
          'bao' => 'CRM_ActivityEntity_DAO_EntityActivity',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Connection type"),
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'activity_entity_connection_type',
            'optionEditPath' => 'civicrm/admin/options/activity_entity_connection_type',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'entity_activity', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'entity_activity', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_activity_entity' => [
        'name' => 'UI_activity_entity',
        'field' => [
          0 => 'activity_id',
          1 => 'entity_table',
          2 => 'entity_id',
          3 => 'record_type_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_entity_activity::1::activity_id::entity_table::entity_id::record_type_id',
      ],
      'index_record_type' => [
        'name' => 'index_record_type',
        'field' => [
          0 => 'activity_id',
          1 => 'record_type_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_entity_activity::0::activity_id::record_type_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
